const stockNames1 = ["Adani Ports",
    "Asian Paints",
    "Axis Bank",
    "Bajaj Auto",
    "Bajaj Finance",
    "Bajaj Finserv",
    "Bharat Petroleum Corporation",
    "Bharti Airtel",
    "Britannia Industries",
    "Cipla",
    "Coal India",
    "Divi's Laboratories",
    "Dr.Reddy's Laboratories",
    "Eicher Motors",
    "Grasim Industries",
    "HCL Technologies",
    "HDFC Bank",
    "HDFC Life Insurance Company",
    "Hero MotoCorp",
    "Hindalco Industries",
    "Hindustan Unilever",
    "Housing Development Finance Corporation",
    "ICICI Bank",
    "ITC",
    "Indian Oil Corporation",
    "IndusInd Bank",
    "Infosys",
    "JSW Steel",
    "Kotak Mahindra Bank",
    "Larsen & Toubro",
    "Mahindra & Mahindra",
    "Maruti Suzuki India",
    "NTPC",
    "Nestle India",
    "Oil & Natural Gas Corporation",
    "Power Grid Corporation of India",
    "Reliance Industries",
    "SBI Life Insurance Company",
    "Shree Cement",
    "State Bank of India",
    "Sun Pharmaceutical Industries",
    "Tata Consultancy Services",
    "Tata Consumer Products",
    "Tata Motors",
    "Tata Steel",
    "Tech Mahindra",
    "Titan Company",
    "UPL",
    "UltraTech Cement",
    "Wipro",]

const script1 = [
    'ADANIPORTS',
    'ASIANPAINT',
    'AXISBANK',
    'BAJAJ-AUTO',
    'BAJFINANCE',
    'BAJAJFINSV',
    'BPCL',
    'BHARTIARTL',
    'BRITANNIA',
    'CIPLA',
    'COALINDIA',
    'DIVISLAB',
    'DRREDDY',
    'EICHERMOT',
    'GRASIM',
    'HCLTECH',
    'HDFCBANK',
    'HDFCLIFE',
    'HEROMOTOCO',
    'HINDALCO',
    'HINDUNILVR',
    'HDFC',
    'ICICIBANK',
    'ITC',
    'IOC',
    'INDUSINDBK',
    'INFY',
    'JSWSTEEL',
    'KOTAKBANK',
    'LT',
    'M&M',
    'MARUTI',
    'NTPC',
    'NESTLEIND',
    'ONGC',
    'POWERGRID',
    'RELIANCE',
    'SBILIFE',
    'SHREECEM',
    'SBIN',
    'SUNPHARMA',
    'TCS',
    'TATACONSUM',
    'TATAMOTORS',
    'TATASTEEL',
    'TECHM',
    'TITAN',
    'UPL',
    'ULTRACEMCO',
    'WIPRO',
]