const stockNames1 = ["Adani Ports",
    "Asian Paints",
    "Axis Bank",
    "Bajaj Auto",
    "Bajaj Finance",
    "Bajaj Finserv",
    "Bharat Petroleum Corporation",
    "Bharti Airtel",
    "Britannia Industries",
    "Cipla",
    "Coal India",
    "Divi's Laboratories",
    "Dr.Reddy's Laboratories",
    "Eicher Motors",
    "Grasim Industries",
    "HCL Technologies",
    "HDFC Bank",
    "HDFC Life Insurance Company",
    "Hero MotoCorp",
    "Hindalco Industries",
    "Hindustan Unilever",
    "Housing Development Finance Corporation",
    "ICICI Bank",
    "ITC",
    "Indian Oil Corporation",
    "IndusInd Bank",
    "Infosys",
    "JSW Steel",
    "Kotak Mahindra Bank",
    "Larsen & Toubro",
    "Mahindra & Mahindra",
    "Maruti Suzuki India",
    "NTPC",
    "Nestle India",
    "Oil & Natural Gas Corporation",
    "Power Grid Corporation of India",
    "Reliance Industries",
    "SBI Life Insurance Company",
    "Shree Cement",
    "State Bank of India",
    "Sun Pharmaceutical Industries",
    "Tata Consultancy Services",
    "Tata Consumer Products",
    "Tata Motors",
    "Tata Steel",
    "Tech Mahindra",
    "Titan Company",
    "UPL",
    "UltraTech Cement",
    "Wipro",]

const script1 = [
    'ADANIPORTS',
    'ASIANPAINT',
    'AXISBANK',
    'BAJAJ-AUTO',
    'BAJFINANCE',
    'BAJAJFINSV',
    'BPCL',
    'BHARTIARTL',
    'BRITANNIA',
    'CIPLA',
    'COALINDIA',
    'DIVISLAB',
    'DRREDDY',
    'EICHERMOT',
    'GRASIM',
    'HCLTECH',
    'HDFCBANK',
    'HDFCLIFE',
    'HEROMOTOCO',
    'HINDALCO',
    'HINDUNILVR',
    'HDFC',
    'ICICIBANK',
    'ITC',
    'IOC',
    'INDUSINDBK',
    'INFY',
    'JSWSTEEL',
    'KOTAKBANK',
    'LT',
    'M&M',
    'MARUTI',
    'NTPC',
    'NESTLEIND',
    'ONGC',
    'POWERGRID',
    'RELIANCE',
    'SBILIFE',
    'SHREECEM',
    'SBIN',
    'SUNPHARMA',
    'TCS',
    'TATACONSUM',
    'TATAMOTORS',
    'TATASTEEL',
    'TECHM',
    'TITAN',
    'UPL',
    'ULTRACEMCO',
    'WIPRO',
]
const script = ["AAPL", "ABMD", "ABNB", "ACGL", "ADBE", "ADI", "ADP", "ADSK", "AEP", "AFRM", "AKAM", "ALGN", "ALNY", "AMAT", "AMD", "AMGN", "AMZN", "ANSS", "APA", "APP", "ARCC", "ARGX", "ASML", "ATVI", "AVGO", "AZN", "AZPN", "BGNE", "BIDU", "BIIB", "BKNG", "BKR", "BMRN", "BNTX", "BRKR", "BSY", "CCEP", "CDNS", "CDW", "CEG", "CERN", "CG", "CGNX", "CHK", "CHKP", "CHRW", "CHTR", "CINF", "CMCSA", "CME", "CNXC", "COIN", "CONE", "COST", "CPRT", "CRWD", "CSCO", "CSGP", "CSX", "CTAS", "CTSH", "CTXS", "CZR", "DDOG", "DISCA", "DISCB", "DISCK", "DISH", "DLTR", "DOCU", "DOX", "DXCM", "EA", "EBAY", "ENTG", "EQIX", "ERIC", "ETSY", "EWBC", "EXAS", "EXC", "EXPD", "EXPE", "FANG", "FAST", "FB", "FCNCA", "FFIV", "FISV", "FITB", "FOX", "FOXA", "FTNT", "FWONA", "FWONK", "GFS", "GILD", "GLPI", "GMAB", "GOOG", "GOOGL", "GRAB", "HAS", "HBAN", "HOLX", "HON", "HSIC", "HST", "HTHT", "HZNP", "ICLR", "IDXX", "IEP", "ILMN", "INCY", "INTC", "INTU", "ISRG", "JBHT", "JD", "JKHY", "KDP", "KHC", "KLAC", "LAMR", "LBRDA", "LBRDK", "LBTYA", "LBTYB", "LBTYK", "LCID", "LI", "LKQ", "LNT", "LOGI", "LPLA", "LRCX", "LSXMA", "LSXMK", "LULU", "LYFT", "MAR", "MCHP", "MDLZ", "MELI", "MKTX", "MNST", "MORN", "MPWR", "MRNA", "MRVL", "MSFT", "MTCH", "MU", "NDAQ", "NDSN", "NFLX", "NICE", "NLOK", "NTAP", "NTES", "NTRS", "NUAN", "NVDA", "NWS", "NWSA", "NXPI", "ODFL", "OKTA", "OLPX", "ON", "ORLY", "OTEX", "PANW", "PARA", "PARAA", "PAYX", "PCAR", "PCTY", "PDD", "PEP", "PFG", "PODD", "POOL", "PTC", "PYPL", "QCOM", "QRVO", "REG", "REGN", "RIVN", "ROKU", "ROST", "RPRX", "RYAAY", "SBAC", "SBNY", "SBUX", "SEDG", "SGEN", "SIRI", "SIVB", "SNPS", "SNY", "SPLK", "SSNC", "STLD", "STX", "SWKS", "TCOM", "TEAM", "TECH", "TER", "TMUS", "TRMB", "TROW", "TSCO", "TSLA", "TTWO", "TW", "TXN", "UAL", "UHAL", "ULTA", "UPST", "VOD", "VRSK", "VRSN", "VRTX", "VTRS", "WBA", "WDAY", "WDC", "WMG", "WTW", "XEL", "XM", "XP", "XRAY", "Z", "ZBRA", "ZG", "ZI", "ZM", "ZNGA", "ZS"]
const USSymbol1 = ["A", "AA", "AAC", "AACG", "AACI", "AACIU", "AACIW", "AADI", "AAIC", "AAIC^B", "AAIC^C", "AAIN", "AAL", "AAM^A", "AAM^B", "AAME", "AAN", "AAOI", "AAON", "AAP", "AAPL", "AAQC", "AAT", "AATC", "AAU", "AAWW", "AB", "ABB", "ABBV", "ABC", "ABCB", "ABCL", "ABCM", "ABEO", "ABEV", "ABG", "ABGI", "ABIO", "ABM", "ABMD", "ABNB", "ABOS", "ABR", "ABR^D", "ABR^E", "ABR^F", "ABSI", "ABST", "ABT", "ABTX", "ABUS", "ABVC", "AC", "ACA", "ACABU", "ACAD", "ACAH", "ACAHU", "ACAHW", "ACAQ", "ACAXU", "ACB", "ACBA", "ACBAU", "ACBAW", "ACC", "ACCD", "ACCO", "ACDI"]
const stockNames = ["Apple Inc. Common Stock", "ABIOMED Inc. Common Stock", "Airbnb Inc. Class A Common Stock", "Arch Capital Group Ltd. Common Stock", "Adobe Inc. Common Stock", "Analog Devices Inc. Common Stock", "Automatic Data Processing Inc. Common Stock", "Autodesk Inc. Common Stock", "American Electric Power Company Inc. Common Stock", "Affirm Holdings Inc. Class A Common Stock", "Akamai Technologies Inc. Common Stock", "Align Technology Inc. Common Stock", "Alnylam Pharmaceuticals Inc. Common Stock", "Applied Materials Inc. Common Stock", "Advanced Micro Devices Inc. Common Stock", "Amgen Inc. Common Stock", "Amazon.com Inc. Common Stock", "ANSYS Inc. Common Stock", "APA Corporation Common Stock", "Applovin Corporation Class A Common Stock", "Ares Capital Corporation Common Stock", "argenx SE American Depositary Shares", "ASML Holding N.V. New York Registry Shares", "Activision Blizzard Inc. Common Stock", "Broadcom Inc. Common Stock", "AstraZeneca PLC American Depositary Shares", "Aspen Technology Inc. Common Stock", "BeiGene Ltd. American Depositary Shares", "Baidu Inc. ADS", "Biogen Inc. Common Stock", "Booking Holdings Inc. Common Stock", "Baker Hughes Company Class A Common Stock", "BioMarin Pharmaceutical Inc. Common Stock", "BioNTech SE American Depositary Share", "Bruker Corporation Common Stock", "Bentley Systems Incorporated Class B Common Stock", "Coca-Cola Europacific Partners plc Ordinary Shares", "Cadence Design Systems Inc. Common Stock", "CDW Corporation Common Stock", "Constellation Energy Corporation Common Stock", "Cerner Corporation Common Stock", "The Carlyle Group Inc. Common Stock", "Cognex Corporation Common Stock", "Chesapeake Energy Corporation Common Stock", "Check Point Software Technologies Ltd. Ordinary Shares", "C.H. Robinson Worldwide Inc. Common Stock", "Charter Communications Inc. Class A Common Stock New", "Cincinnati Financial Corporation Common Stock",
    "Comcast Corporation Class A Common Stock", "CME Group Inc. Class A Common Stock", "Concentrix Corporation Common Stock", "Coinbase Global Inc. Class A Common Stock", "CyrusOne Inc Common Stock", "Costco Wholesale Corporation Common Stock", "Copart Inc. (DE) Common Stock", "CrowdStrike Holdings Inc. Class A Common Stock", "Cisco Systems Inc. Common Stock (DE)", "CoStar Group Inc. Common Stock", "CSX Corporation Common Stock", "Cintas Corporation Common Stock", "Cognizant Technology Solutions Corporation Class A Common Stock", "Citrix Systems Inc. Common Stock", "Caesars Entertainment Inc. Common Stock", "Datadog Inc. Class A Common Stock", "Discovery Inc. Series A Common Stock", "Discovery Inc. Series B Common Stock", "Discovery Inc. Series C Common Stock", "DISH Network Corporation Class A Common Stock", "Dollar Tree Inc. Common Stock", "DocuSign Inc. Common Stock", "Amdocs Limited Ordinary Shares", "DexCom Inc. Common Stock", "Electronic Arts Inc. Common Stock", "eBay Inc. Common Stock", "Entegris Inc. Common Stock", "Equinix Inc. Common Stock REIT", "Ericsson American Depositary Shares", "Etsy Inc. Common Stock", "East West Bancorp Inc. Common Stock", "Exact Sciences Corporation Common Stock", "Exelon Corporation Common Stock", "Expeditors International of Washington Inc. Common Stock", "Expedia Group Inc. Common Stock", "Diamondback Energy Inc. Commmon Stock", "Fastenal Company Common Stock", "Meta Platforms Inc. Class A Common Stock", "First Citizens BancShares Inc. Class A Common Stock", "F5 Inc. Common Stock", "Fiserv Inc. Common Stock", "Fifth Third Bancorp Common Stock", "Fox Corporation Class B Common Stock", "Fox Corporation Class A Common Stock", "Fortinet Inc. Common Stock", "Liberty Media Corporation Series A Liberty Formula One Common Stock", "Liberty Media Corporation Series C Liberty Formula One Common Stock", "GlobalFoundries Inc. Ordinary Shares", "Gilead Sciences Inc. Common Stock",
    "Gaming and Leisure Properties Inc. Common Stock", "Genmab A/S ADS", "Alphabet Inc. Class C Capital Stock", "Alphabet Inc. Class A Common Stock", "Grab Holdings Limited Class A Ordinary Shares", "Hasbro Inc. Common Stock", "Huntington Bancshares Incorporated Common Stock", "Hologic Inc. Common Stock", "Honeywell International Inc. Common Stock", "Henry Schein Inc. Common Stock", "Host Hotels & Resorts Inc. Common Stock", "Huazhu Group Limited American Depositary Shares", "Horizon Therapeutics Public Limited Company Ordinary Shares", "ICON plc Ordinary Shares", "IDEXX Laboratories Inc. Common Stock", "Icahn Enterprises L.P. Common Stock", "Illumina Inc. Common Stock", "Incyte Corp. Common Stock", "Intel Corporation Common Stock", "Intuit Inc. Common Stock", "Intuitive Surgical Inc. Common Stock", "J.B. Hunt Transport Services Inc. Common Stock", "JD.com Inc. American Depositary Shares", "Jack Henry & Associates Inc. Common Stock", "Keurig Dr Pepper Inc. Common Stock", "The Kraft Heinz Company Common Stock", "KLA Corporation Common Stock", "Lamar Advertising Company Class A Common Stock", "Liberty Broadband Corporation Class A Common Stock", "Liberty Broadband Corporation Class C Common Stock", "Liberty Global plc Class A Ordinary Shares", "Liberty Global plc Class B Ordinary Shares", "Liberty Global plc Class C Ordinary Shares", "Lucid Group Inc. Common Stock", "Li Auto Inc. American Depositary Shares", "LKQ Corporation Common Stock", "Alliant Energy Corporation Common Stock", "Logitech International S.A. Ordinary Shares", "LPL Financial Holdings Inc. Common Stock", "Lam Research Corporation Common Stock", "Liberty Media Corporation Series A Liberty SiriusXM Common Stock", "Liberty Media Corporation Series C Liberty SiriusXM Common Stock", "lululemon athletica inc. Common Stock", "Lyft Inc. Class A Common Stock", "Marriott International Class A Common Stock", "Microchip Technology Incorporated Common Stock",
    "Mondelez International Inc. Class A Common Stock", "MercadoLibre Inc. Common Stock", "MarketAxess Holdings Inc. Common Stock", "Monster Beverage Corporation", "Morningstar Inc. Common Stock", "Monolithic Power Systems Inc. Common Stock", "Moderna Inc. Common Stock", "Marvell Technology Inc. Common Stock", "Microsoft Corporation Common Stock", "Match Group Inc. Common Stock", "Micron Technology Inc. Common Stock", "Nasdaq Inc. Common Stock", "Nordson Corporation Common Stock", "Netflix Inc. Common Stock", "NICE Ltd American Depositary Shares", "NortonLifeLock Inc. Common Stock", "NetApp Inc. Common Stock", "NetEase Inc. American Depositary Shares", "Northern Trust Corporation Common Stock", "Nuance Communications Inc. Common Stock", "NVIDIA Corporation Common Stock", "News Corporation Class B Common Stock", "News Corporation Class A Common Stock", "NXP Semiconductors N.V. Common Stock", "Old Dominion Freight Line Inc. Common Stock", "Okta Inc. Class A Common Stock", "Olaplex Holdings Inc. Common Stock", "ON Semiconductor Corporation Common Stock", "OReilly Automotive Inc. Common Stock", "Open Text Corporation Common Shares", "Palo Alto Networks Inc. Common Stock", "Paramount Global Class B Common Stock", "Paramount Global Class A Common Stock", "Paychex Inc. Common Stock", "PACCAR Inc. Common Stock", "Paylocity Holding Corporation Common Stock", "Pinduoduo Inc. American Depositary Shares", "PepsiCo Inc. Common Stock", "Principal Financial Group Inc Common Stock", "Insulet Corporation Common Stock", "Pool Corporation Common Stock", "PTC Inc. Common Stock", "PayPal Holdings Inc. Common Stock", "QUALCOMM Incorporated Common Stock", "Qorvo Inc. Common Stock", "Regency Centers Corporation Common Stock", "Regeneron Pharmaceuticals Inc. Common Stock", "Rivian Automotive Inc. Class A Common Stock", "Roku Inc. Class A Common Stock", "Ross Stores Inc. Common Stock", "Royalty Pharma plc Class A Ordinary Shares",
    "Ryanair Holdings plc American Depositary Shares", "SBA Communications Corporation Class A Common Stock", "Signature Bank Common Stock", "Starbucks Corporation Common Stock", "SolarEdge Technologies Inc. Common Stock", "Seagen Inc. Common Stock", "Sirius XM Holdings Inc. Common Stock", "SVB Financial Group Common Stock", "Synopsys Inc. Common Stock", "Sanofi ADS", "Splunk Inc. Common Stock", "SS&C Technologies Holdings Inc. Common Stock", "Steel Dynamics Inc.", "Seagate Technology Holdings PLC Ordinary Shares (Ireland)", "Skyworks Solutions Inc. Common Stock", "Trip.com Group Limited American Depositary Shares", "Atlassian Corporation Plc Class A Ordinary Shares", "Bio-Techne Corp Common Stock", "Teradyne Inc. Common Stock", "T-Mobile US Inc. Common Stock", "Trimble Inc. Common Stock", "T. Rowe Price Group Inc. Common Stock", "Tractor Supply Company Common Stock", "Tesla Inc. Common Stock", "Take-Two Interactive Software Inc. Common Stock", "Tradeweb Markets Inc. Class A Common Stock", "Texas Instruments Incorporated Common Stock", "United Airlines Holdings Inc. Common Stock", "Amerco Common Stock", "Ulta Beauty Inc. Common Stock", "Upstart Holdings Inc. Common stock", "Vodafone Group Plc American Depositary Shares", "Verisk Analytics Inc. Common Stock", "VeriSign Inc. Common Stock", "Vertex Pharmaceuticals Incorporated Common Stock", "Viatris Inc. Common Stock", "Walgreens Boots Alliance Inc. Common Stock", "Workday Inc. Class A Common Stock", "Western Digital Corporation Common Stock", "Warner Music Group Corp. Class A Common Stock", "Willis Towers Watson Public Limited Company Ordinary Shares", "Xcel Energy Inc. Common Stock", "Qualtrics International Inc. Class A Common Stock", "XP Inc. Class A Common Stock", "DENTSPLY SIRONA Inc. Common Stock", "Zillow Group Inc. Class C Capital Stock", "Zebra Technologies Corporation Class A Common Stock", "Zillow Group Inc. Class A Common Stock", "ZoomInfo Technologies Inc Class A Common Stock", "Zoom Video Communications Inc. Class A Common Stock", "Zynga Inc. Class A Common Stock", "Zscaler Inc. Common Stock"]
module.exports = { stockNames, script }